backend:
  name: github
  repo: Melonhead60/melonhead60.github.io
  branch: main                        # Your default branch
  base_url: https://melonhead60.github.io
  auth_type: implicit  # Required for GitHub Pages

media_folder: "src/images"            # Where original images are stored
public_folder: "/images"              # Path in the built site

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }