backend:
  name: github
  repo: Melonhead60/melonhead60.github.io
  branch: main
  base_url: https://melonhead60.github.io  # Must be exact
  auth_type: implicit
  app_id: Ov23liSi7TaRogD19hLc  # From GitHub OAuth App
  # Critical: Disable Netlify-style auth
  auth_endpoint: null

media_folder: "src/images"            # Where original images are stored
public_folder: "/images"              # Path in the built site

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }