backend:
  name: github
  repo: Melonhead60/melonhead60.github.io
  branch: main
  # Remove base_url as it's not needed for GitHub auth
  auth_type: implicit
  app_id: Ov23liSi7TaRogD19hLc  # From GitHub OAuth App
  auth_endpoint: https://github.com/login/oauth/authorize
  # GitHub's OAuth scope needs to include repo for full access
  auth_scope: "repo"
  # Explicitly disable Netlify-specific features
  identity_url: null
  gateway_url: null

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }