backend:
  name: github
  repo: Melonhead60/melonhead60.github.io
  branch: main
  
  # GitHub OAuth Config
  auth_type: implicit
  app_id: Ov23liSi7TaRogD19hLc
  
  # Explicit GitHub OAuth endpoints
  auth_endpoint: https://github.com/login/oauth/authorize
  
  # Nuclear option to disable all Netlify services
  identity: false
  gateway: null
  
  # Required scope
  auth_scope: "repo"

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }